### ISSUE TITLE
k-Anonymity PDF discrepancy

### ISSUE THREAD

**Issue by jkav77** [uvm-plaid/programming-dp#43] opened 2023-11-01 01:43 UTC
I noticed a typo in the PDF downloaded from programming-dp.com/book.pdf that seems to be fixed already in the repo. Cell 75 is `ch2.ipynb` outputs the result `False`, but the pdf says `True` on page 18. 

I appreciate the book so I wanted to point out this minor discrepancy.

**Comment by chikeabuah** [comment] 2024-01-07 13:24
@dangerginger thank you very much for reading the book, and pointing out this issue! 

this was caused by a quality update I made to the relevant dataset here https://github.com/uvm-plaid/programming-dp/commit/7f546df0b36bc0a583cb3c60956dcabbfd028587 which ended up unintentionally removing outliers.

This issue has been fixed by adding outliers in a recent commit: https://github.com/uvm-plaid/programming-dp/commit/a4db91ac368d907393a8e3a00ce57c9fc7ae9c07

**Closed as completed by chikeabuah** 2024-01-07 13:24 UTC
